// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mBS9XenARAASlopCmNtUMriErPgCoBs',
    appId: '1:842839779614:web:a47c05bdd66898ba77010f',
    messagingSenderId: '842839779614',
    projectId: 'espiot-edc59',
    authDomain: 'espiot-edc59.firebaseapp.com',
    storageBucket: 'espiot-edc59.firebasestorage.app',
    measurementId: 'G-F394CMW1GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAO-sqy24kqhCO0RUWRIxa3daBk-c9RE',
    appId: '1:842839779614:android:0ff5393cd32f548077010f',
    messagingSenderId: '842839779614',
    projectId: 'espiot-edc59',
    storageBucket: 'espiot-edc59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmLRdZM6q7zhaLsUyzQokTQgJioOuf6IE',
    appId: '1:842839779614:ios:341d8a4f497c9c4277010f',
    messagingSenderId: '842839779614',
    projectId: 'espiot-edc59',
    storageBucket: 'espiot-edc59.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmLRdZM6q7zhaLsUyzQokTQgJioOuf6IE',
    appId: '1:842839779614:ios:341d8a4f497c9c4277010f',
    messagingSenderId: '842839779614',
    projectId: 'espiot-edc59',
    storageBucket: 'espiot-edc59.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1mBS9XenARAASlopCmNtUMriErPgCoBs',
    appId: '1:842839779614:web:9276bb208853798c77010f',
    messagingSenderId: '842839779614',
    projectId: 'espiot-edc59',
    authDomain: 'espiot-edc59.firebaseapp.com',
    storageBucket: 'espiot-edc59.firebasestorage.app',
    measurementId: 'G-L9QV7E906D',
  );
}
